### ISSUE TITLE
答案的准确度不够，与可以找到出处的文章内容有差别

### ISSUE THREAD

**Issue by zjx-immersion** [EasonAndLily/OOCL#10]
https://github.com/EasonAndLily/OOCL/blob/ee4d2bfd2d09542d1d159a7bc7c127672ac01e07/%E9%AA%8C%E6%94%B6%E5%8D%A1/tasking.yml#L9

引用仝老师的原文
```
所谓各自独立，说的就是在我们划分任务的过程中，每一个任务都对应一个代码块或一个函数，这些代码块和函数，是互相不包含的（不是不依赖，这是翻译的问题，各自独立的独立指的是Exclusive不是Independent）。

所谓的完全穷尽，说的是我们需要穷尽这个代码块或函数里所有的输入和输出。不能遗漏任何一个输入，任何一个输出。
```

所以从选项3、4来说没法很容易的解释清楚 谁对谁错 为什么？

**Comment by jialiu-github** [comment]
fixed
      - "任务之间需要各自独立"
      - "各自独立是指一个任务不能引用另外一个任务的结果"
      - "能够将所有的任务名字写出来，就算完全穷尽了"
      - "完全穷尽是指所有任务的输入输出必须都很明确"
