### ISSUE TITLE
选项1 和 选项3 比较难判断对错

### ISSUE THREAD

**Issue by zjx-immersion** [EasonAndLily/OOCL#11]
https://github.com/EasonAndLily/OOCL/blob/ee4d2bfd2d09542d1d159a7bc7c127672ac01e07/%E9%AA%8C%E6%94%B6%E5%8D%A1/tasking.yml#L16

选项1 和 选项3 比较难判断对错，选项3也能说得过去，学生说我这个函数就是用来做正数相加的，也美毛病，改一个更明显点儿的错误吧？

**Comment by jialiu-github** [comment]
fixed，选项3改成了：
        ```
        求和函数
        输入：
          importArray: [Number]
        输出：
          sum: string
        ```
