### ISSUE TITLE
选项三也是错误的

### ISSUE THREAD

**Issue by zjx-immersion** [EasonAndLily/OOCL#18]
https://github.com/EasonAndLily/OOCL/blob/ee4d2bfd2d09542d1d159a7bc7c127672ac01e07/%E9%AA%8C%E6%94%B6%E5%8D%A1/js_basics.yml#L66

选项三的答案应该是 “23456”  ？

ste.subString 应该是  str.substring ?

**Comment by jialiu-github** [comment]
change subString to substring.
