### ISSUE TITLE
测验题反馈

### ISSUE THREAD

**Issue by zjx-immersion** [EasonAndLily/OOCL#2]
### HTML  
3、4、7、8  覆盖的内容都不是平时开发会经常涉及到的，建议替换，可以从整个HTML文档和一些常用标签的使用上提问

### CSS
第三题的代码示例有问题？

### JS
第9题没啥意义，还多程序员都不会，也不是要求他们学的，建议可以换成对于map reduce sum之类数组操作方法的提问

### Java 
14题是单选， 但是提问的方式给人感觉是多选

### 补充
建议每类题都至少有1-2道多选增加难度

总共有49道题，不知道是不是我数错了？

**Comment by zjx-immersion** [comment]
我建议50题外，再加两道题：一道是关于软件工程的（瀑布、敏捷）  一道是关于程序员日常开发需要做哪些事儿 或者是职责是什么的

**Comment by nealseah** [comment]
## Java
* 2题的答案要不要再考虑一下？
* 15题还顺便考察了“==“吧。这题的本意就是综合考察两个知识点么？如果不是，一个建议哈，一题考察一个知识点的话，方便分析学员某个知识点的掌握情况。

**Comment by zhengdianfang** [comment]
@zjx-immersion 已修改反馈的内容，部分题目改成了多选

**Comment by EasonAndLily** [comment]
感谢各位的反馈，已经做了一下修改：
1.  增加了多选题来提升题目难度。
2. 增加了一道题，目前总共50道题目。
3. 增加了一道软件工程方面的题目。
