### ISSUE TITLE
最后2到自查题 有点儿深

### ISSUE THREAD

**Issue by zjx-immersion** [EasonAndLily/OOCL#21]
https://github.com/EasonAndLily/OOCL/blob/ee4d2bfd2d09542d1d159a7bc7c127672ac01e07/%E9%AA%8C%E6%94%B6%E5%8D%A1/js_basics.yml#L377

1. 最后2题 Lambda 概念本身不太好理解 加上链式调用在第一周中基本美涉及，所以吧这两题可以换成箭头函数 和 函数作为参数 如何？

2. 所有自查题的选项都改为 ：
- 听说过，但不了解
- 用过但并不理解概念
- 理解概念但没练习过
- 理解概念并在练习中使用过
- 知道为何要在练习中使用此概念，并明白在练习中如何使用它
- 能够识别该技术的主要应用场景或者解决的问题，并能熟练使用

**Comment by jialiu-github** [comment]
ok! fixed!
