### ISSUE TITLE
这句注释建议改成，new Vue({ data: { html: '<spa>xxxx' })， 这样应该更好理解

### ISSUE THREAD

**Issue by zhengdianfang** [EasonAndLily/OOCL#22]
https://github.com/EasonAndLily/OOCL/blob/805fcfddb51990c2a4b8fd3484f8bbd5a83c885c/%E9%AA%8C%E6%94%B6%E5%8D%A1/vue.yml#L4

**Comment by jialiu-github** [comment]
fixed
