### ISSUE TITLE
自查题中 重构 和 坏味道识别 分开来问

### ISSUE THREAD

**Issue by zjx-immersion** [EasonAndLily/OOCL#24]
1.自查题中 重构 和 坏味道识别 分开来问

2.把自查题的答案调整成：
- 听说过，但不了解
- 用过但并不理解概念
- 理解概念但没练习过
- 理解概念并在练习中使用过
- 知道为何要在练习中使用此概念，并明白在练习中如何使用它
- 能够识别该技术的主要应用场景或者解决的问题，并能熟练使用

https://github.com/EasonAndLily/OOCL/blob/805fcfddb51990c2a4b8fd3484f8bbd5a83c885c/%E9%AA%8C%E6%94%B6%E5%8D%A1/tdd.yml#L256

**Comment by EasonAndLily** [comment]
已经改过来了
