### ISSUE TITLE
Java OO 中加入还需加入几种题

### ISSUE THREAD

**Issue by zjx-immersion** [EasonAndLily/OOCL#27]
https://github.com/EasonAndLily/OOCL/blob/805fcfddb51990c2a4b8fd3484f8bbd5a83c885c/%E9%AA%8C%E6%94%B6%E5%8D%A1/java_basics_and_oo.yml#L1
Java OO 中加入还需加入几种题
1. 对于OO设计的基础题，比如给一段需求，让学员选择落地到代码有哪些类，这些类之间的关系
2. 对于Gradle需要有如何加入依赖和管理依赖的题，场景是：之后会让他们引入各种类库进行开发
3. 需要考核一些对于Maven项目目录结构, src main test java 之类的这种结构 和parkage的使用

**Comment by EasonAndLily** [comment]
done
