### ISSUE TITLE
@MockBean 会在哪张任务卡中用到呢？

### ISSUE THREAD

**Issue by zjx-immersion** [EasonAndLily/OOCL#28]
https://github.com/EasonAndLily/OOCL/blob/805fcfddb51990c2a4b8fd3484f8bbd5a83c885c/%E9%AA%8C%E6%94%B6%E5%8D%A1/restful.yml#L105

MockBean主要是用来做分层单元则是的，比如测controller的时候，把相关依赖都mock了，但是在我们的教学中基本不会涉及，因为对学员来说有点儿太难了，一般就是controller api test直接测试端到端（包括JPA）.

可以出2道Controller API Testing如何写的代码题：
```java
    @Test
    public void should_get_400_if_employee_id_conflicts() throws Exception {
        final String duplicatedId = "employee-01";

        mvc.perform(post("/parkingboys")
            .content(toJsonString(CreateParkingBoyRequest.create(duplicatedId)))
            .contentType(MediaType.APPLICATION_JSON))
            .andExpect(status().isCreated());

        mvc.perform(post("/parkingboys")
            .content(toJsonString(CreateParkingBoyRequest.create(duplicatedId)))
            .contentType(MediaType.APPLICATION_JSON))
            .andExpect(status().isBadRequest());
    }
```
类似面代码 如何测post 如何测get,如何验证返回为json的结果等
去年我们培训的一版实现：https://github.com/tws-graduate-bootcamp/sprint-boot-multi-tier-test/blob/answers/src/test/java/com/oocl/web/sampleWebApp/ParkingBoyResourceTests.java

**Comment by zhengdianfang** [comment]
我是用MockBean 来mock repository
