### ISSUE TITLE
此题的出处是哪张任务卡呢？ 

### ISSUE THREAD

**Issue by zjx-immersion** [EasonAndLily/OOCL#31]
https://github.com/EasonAndLily/OOCL/blob/805fcfddb51990c2a4b8fd3484f8bbd5a83c885c/%E9%AA%8C%E6%94%B6%E5%8D%A1/spring.yml#L212

我印象中AOP对毕业生太难，一个是不好理解，一个是对于初级开发来说应用的场景相对较少，是否考虑去掉？

**Comment by zhengdianfang** [comment]
已删除
