### ISSUE TITLE
建议本节验收卡覆盖一些ORM和JDBC的基础概念题

### ISSUE THREAD

**Issue by EasonAndLily** [EasonAndLily/OOCL#8]
https://github.com/EasonAndLily/OOCL/blob/34e8bd7985cb74b68ce51ee0247f73a152542d1e/%E9%AA%8C%E6%94%B6%E5%8D%A1/persistence.yml#L1

**Comment by zhengdianfang** [comment]
已添加一道jdbc概念题和两道ORM概念题
