### ISSUE TITLE
题目主干看不出来考什么，需要具体一点儿，

### ISSUE THREAD

**Issue by zjx-immersion** [EasonAndLily/OOCL#9]
1.题目主干看不出来考什么，需要具体一点儿
2.答案选项内容不够结构化和清楚，需要把系统提供的数据 输入 输出 标示清楚

https://github.com/EasonAndLily/OOCL/blob/805fcfddb51990c2a4b8fd3484f8bbd5a83c885c/%E9%AA%8C%E6%94%B6%E5%8D%A1/tasking.yml#L187

**Comment by jialiu-github** [comment]
fixed
